version: '3'
services:
  database:
    restart: always
    image: postgres:latest
    ports:
      - "6564:5432"
    environment:
      - POSTGRES_DB=jobdealer
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  backend:
    restart: always
    build: ./backend/
    ports:
      - "6565:8080"
